# Home Assistant add-on: LibreCoach
name: "LibreCoach"
version: "1.0.55"
slug: "librecoach"
description: "Smart home control for your RV"
url: "https://librecoach.com"
maintainer: "Ted Lanham <Backroads4Me@gmail.com>"
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
init: false
hassio_api: true
hassio_role: manager
homeassistant_api: true
privileged:
  - NET_ADMIN
  - NET_RAW
ingress: true
ingress_port: 8099
panel_icon: "mdi:rv-truck"
panel_title: "LibreCoach"
host_network: true
host_dbus: true
devices:
  - /dev/bus/usb
uart: true
map:
  - share:rw
  - config:rw
options:
  confirm_nodered_takeover: false
  prevent_flow_updates: false
  debug_logging: false
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "librecoach"
  mqtt_pass: "One23four"
  can_interface: "can0"
  victron_enabled: true
  microair_enabled: false
  microair_email: ""
  microair_password: ""
  ble_scan_interval: 30
  beta_enabled: false
schema:
  confirm_nodered_takeover: bool
  prevent_flow_updates: bool
  debug_logging: bool
  mqtt_host: str?
  mqtt_port: "int(1,65535)?"
  mqtt_user: str
  mqtt_pass: password
  can_interface: str
  victron_enabled: bool?
  microair_enabled: bool?
  microair_email: str?
  microair_password: password?
  ble_scan_interval: "int(10,300)?"
  beta_enabled: bool?
image: ghcr.io/backroads4me/{arch}-librecoach-beta
