# Home Assistant add-on: LibreCoach
name: "LibreCoach"
version: "1.0.6"
slug: "librecoach"
description: "LibreCoach: For controlling and monitoring RV systems"
url: "https://librecoach.com"
maintainer: "Ted Lanham <Backroads4Me@gmail.com>"
post_update: |
  Update complete. Start the LibreCoach add-on to apply the update.
  It will run the orchestrator and stop on its own when finished.
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: manual
init: false
hassio_api: true
hassio_role: manager
homeassistant_api: true
map:
  - share:rw
options:
  confirm_nodered_takeover: false
  mqtt_user: "librecoach"
  mqtt_pass: "One23four"
  mqtt_topic_raw: "can/raw"
  mqtt_topic_send: "can/send"
  mqtt_topic_status: "can/status"
  can_interface: "can0"
  can_bitrate: "250000"
  debug_logging: false
schema:
  confirm_nodered_takeover: bool
  mqtt_user: str
  mqtt_pass: password
  mqtt_topic_raw: str
  mqtt_topic_send: str
  mqtt_topic_status: str
  can_interface: str
  can_bitrate: list(125000|250000|500000|1000000)
  debug_logging: bool
image: ghcr.io/backroads4me/{arch}-librecoach-beta
