# Home Assistant add-on: LibreCoach
name: "LibreCoach"
version: "1.0.16"
slug: "librecoach"
description: "LibreCoach: For controlling and monitoring RV systems"
url: "https://librecoach.com"
maintainer: "Ted Lanham <Backroads4Me@gmail.com>"
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
init: false
hassio_api: true
hassio_role: manager
homeassistant_api: true
privileged:
  - NET_ADMIN
  - NET_RAW
host_network: true
host_dbus: true
devices:
  - /dev/bus/usb
uart: true
map:
  - share:rw
options:
  victron_enabled: true
  microair_enabled: false
  microair_email: ""
  microair_password: ""
  confirm_nodered_takeover: false
  beta_enabled: false
  debug_logging: false
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "librecoach"
  mqtt_pass: "One23four"
  mqtt_topic_raw: "can/raw"
  mqtt_topic_send: "can/send"
  mqtt_topic_status: "can/status"
  can_interface: "can0"
  can_bitrate: "250000"
schema:
  victron_enabled: bool
  microair_enabled: bool
  microair_email: str?
  microair_password: password?
  confirm_nodered_takeover: bool
  beta_enabled: bool
  debug_logging: bool
  mqtt_host: str?
  mqtt_port: "int(1,65535)?"
  mqtt_user: str
  mqtt_pass: password
  mqtt_topic_raw: str
  mqtt_topic_send: str
  mqtt_topic_status: str
  can_interface: str
  can_bitrate: list(125000|250000|500000|1000000)
image: ghcr.io/backroads4me/{arch}-librecoach-beta
